@baseurl = http://localhost:5000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyLTc3c3ZmNyIsImlhdCI6MTcwNDM1ODk1MiwiZXhwIjoxNzA0MzYyNTUyfQ.eJYnYKnAHlB3BhHQYbYushxDFZmWNT9TWgi8CwoKbfM

# __________________________________________________ Authentication

### POST Login to get JWT token
POST {{baseurl}}/auth/login
Content-Type: application/json

{
  "username": "waltywinner",
  "password": "clu93oab355xgx"
}

# __________________________________________________ Redis Operations

### GET all app keys
GET {{baseurl}}/redis/all-keys
Authorization: Bearer {{accessToken}}

### GET key for entity
GET {{baseurl}}/redis/get/user
Authorization: Bearer {{accessToken}}

### GET key for entity
GET {{baseurl}}/redis/get/blog
Authorization: Bearer {{accessToken}}

### DELETE specific key for entity
DELETE {{baseurl}}/redis/delete/example_app/example
Authorization: Bearer {{accessToken}}

# __________________________________________________ User-specific Operations

### GET specific key entity
GET {{baseurl}}/redis/get/user/jane
Authorization: Bearer {{accessToken}}

### POST set key for entry
POST {{baseurl}}/redis/set/user/jane
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "value": {
    "userId": 4,
    "username": "jane_doe",
    "email": "jane@example.com",
    "createdAt": "2023-03-01T14:30:00Z",
    "updatedAt": "2023-03-10T10:45:00Z",
    "tags": ["designer", "ui/ux"]
  }
}

# __________________________________________________ Blog-specific Operations

### GET specific key for entity
GET {{baseurl}}/redis/get/blog/101
Authorization: Bearer {{accessToken}}

### POST set key for blog entry
POST {{baseurl}}/redis/set/blog/101
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "value": {
    "blogId": 101,
    "title": "Exploring Redis in Web Development",
    "content": "Redis is a powerful tool for caching and data storage. Learn how to use Redis in web development.",
    "author": "John Doe",
    "createdAt": "2023-04-05T09:15:00Z",
    "updatedAt": "2023-04-10T14:20:00Z",
    "tags": ["redis", "web development"]
  }
}
